name: video_controls
description: A wrapper around video_player to show customizable controls for Flutter videos.
version: 0.1.0
homepage: https://pub.dev/packages/video_controls
repository: https://github.com/Levi-Lesches/video_controls


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
